export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const LIST_PRODUCT_DETAIL_REQUEST = 'List_PRODUCT_REQUEST';
export const LIST_PRODUCT_DETAIL_SUCCESS = 'List_PRODUCT_SUCCESS';
export const LIST_PRODUCT_DETAIL_FAIL = 'List_PRODUCT_FAIL';
